### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by jankais3r** [aschaper/homebridge-sesame#7]
I was debugging some other Homebridge plugin so I had a debug instance running when I got the following error from Sesame. I think it was caused by my wifi dongle being offline at that time. Just posting it here in case anyone would be interested in fixing it.
```
[7/15/2019, 9:21:25 PM] [Sesame] Sesame is unresponsive, forcing a status sync...
[7/15/2019, 9:21:28 PM] [Sesame] Unable to get lock state. Error: Task failed, got error BRIDGE_CONNECTION_ERROR
(node:5843) UnhandledPromiseRejectionWarning: Error: Task failed, got error BRIDGE_CONNECTION_ERROR
    at Client.<anonymous> (/opt/nodejs/lib/node_modules/homebridge-sesame/dist/lib/Client.js:82:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/nodejs/lib/node_modules/homebridge-sesame/dist/lib/Client.js:4:58)
(node:5843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aschzero** [comment]
Thanks for letting me know about this issue! I'll start working on a fix to handle this better.
